### ISSUE TITLE
(Sub-Issue) Look into GitHub Merge Queue

### ISSUE THREAD

**Issue by sanjeevz3009** [ONSdigital/generator-ons-javascript-template#12]
This is a sub-issue of issue #11 

As a repository maintainer, I want to investigate and enable GitHub Merge Queue, so that pull requests are merged in an orderly and automated manner without causing conflicts. 

**Tasks:**
- [ ] Research how GitHub Merge Queue works and assess its benefits for the project.
- [ ] Enable GitHub Merge Queue on the repository.
- [ ] test the queue with a sample PR and verify that it is processed correctly.
- [ ] Document it on the README.md.
